<?php
declare(strict_types=1);

require __DIR__ . '/../shared/header.php';
?>
<section class="page-header">
    <div>
        <h2>Blockchain Ledger</h2>
        <p>Review every block generated by the voting process. Integrity checks ensure zero tampering.</p>
    </div>
    <div class="header-actions">
        <button class="ghost-button" id="verifyChain" type="button">Verify integrity</button>
        <span class="status-pill" id="chainStatus">Pending verification</span>
    </div>
</section>

<section class="panel">
    <header>
        <div>
            <h3>Block explorer</h3>
            <p>Search and filter the ledger. Use the quick filters for vote transactions or system events.</p>
        </div>
        <div class="tab-buttons">
            <button class="ghost-button active" data-filter="all" type="button">All</button>
            <button class="ghost-button" data-filter="vote" type="button">Votes</button>
            <button class="ghost-button" data-filter="genesis" type="button">Genesis &amp; system</button>
        </div>
    </header>
    <div class="table-wrapper">
        <table class="data-table" id="blockchainTable">
            <thead>
            <tr>
                <th>#</th>
                <th>Hash</th>
                <th>Previous</th>
                <th>Nonce</th>
                <th>Type</th>
                <th>Timestamp</th>
            </tr>
            </thead>
            <tbody>
            <tr><td colspan="6">Loading blockchain...</td></tr>
            </tbody>
        </table>
    </div>
</section>

<section class="panel">
    <header>
        <div>
            <h3>Block details</h3>
            <p>Select a block to inspect its payload and verify chain linkage.</p>
        </div>
    </header>
    <pre class="code-view" id="blockPayload">Choose a block to view the raw JSON payload.</pre>
</section>

<?php require __DIR__ . '/../shared/footer.php'; ?>

